# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6ebbb33c-59fd-4174-88a8-188370bab79d";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1e3fae3e-a834-4e1b-b933-609305219022";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/65A4-0C28";
      fsType = "vfat";
      options = [ "umask=0077" "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1d3f8eff-57f1-49fa-994d-3d5c07b60234";
      fsType = "ext4";
    };

  fileSystems."/media/games" =
    { device = "/dev/disk/by-uuid/2e52fa98-71ae-4225-86a4-93663a6e9d4a";
      fsType = "ext4";
    };

  fileSystems."/media/master" =
    { device = "/dev/disk/by-uuid/879f2a8e-eec0-40c7-9fb5-a815084c666e";
      fsType = "ext4";
    };

  fileSystems."/media/primary" =
    { device = "/dev/disk/by-uuid/baca06df-55db-4c73-a7cc-177871b93b14";
      fsType = "ext4";
    };

  fileSystems."/media/secondary" =
    { device = "/dev/disk/by-uuid/40427651-d147-4d21-afc6-4a0cd3705ef6";
      fsType = "ext4";
    };

  fileSystems."/media/backup" =
    { device = "/dev/disk/by-uuid/42c4e372-48bd-4973-99ea-af8718526293";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5aa5bdb4-cea1-4df0-a2cb-19afececb667"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
