#!/usr/bin/env bash

#---------------#
#  newfile-nix  #
#---------------#

#
# Quickly create new .nix files with common defaults already written by passing
# one or more arguments, the first being the filename and the rest as required
# inputs for the module
#

# exit the program and output the error message passed to the function
fatal () {
  echo $1
  exit 1
}

# convert the given filename into title-case for the header
make_title () {
  local input="$1"
  local words
  local word
  local title

  words="${input//[-_]/ }"      # change delimiters to spaces

  for word in $words; do
    title+="${word^} "                # convert first letter of each word to upper
  done
  title="${title% }"                  # trim trailing space

  echo "$title"
}

# create a 3-line header like the one at the top of this file with
# enough dashes to keep each line the same length as the others
make_header () {
  local title="$1"
  local len=${#title}
  local dashes=$(printf '%*s' "$((len + 4))" '' | command tr ' ' '-')
  printf '#%s#\n#  %s  #\n#%s#\n' "$dashes" "$title" "$dashes"
}

# Make sure there's at least 1 argument (the file name)
if [[ $# < 1 ]]
then
  fatal "not enough arguments"
fi

input_path="$1"

if [[ "$1" == */* ]]; then            # if the filename contains a slash
  name="${input_path##*/}"            # trim leading folders from path
  filedir="${input_path%/*}"          # find target file directory
else
  name="${input_path}"
  filedir="$PWD"
fi

filename="${name%%.nix}"              # trim file extension if supplied
title=$(make_title "$filename")
header=$(make_header "$title")
shift

if [[ $# == 0 ]]
then
  inputs_string="{ ... }:"            # default value if no inputs are supplied
fi

# Here we create a string formatted as "{ $1, $2, $3, ... }:" containing all arguments
# (if inputs are provided)
if [[ $# > 0 ]]
then 
  inputs_string="{ "

  for arg in "$@"
  do
    inputs_string+="${arg%,}, "      # trim commas from arguments if supplied
  done

  inputs_string="$inputs_string... }:"
fi

filepath="${filedir}/$filename.nix"

# Now we make a title out of the given filename and pass that to make_header
command cat <<EOF >$filepath
# $filepath

$header

$inputs_string

{

}
EOF

exit 0
