#!/usr/bin/env bash

#---------------#
#  newfile-nix  #
#---------------#

#
# Quickly create new .nix files with common defaults already written by passing
# one or more arguments, the first being the filename and the rest as required
# inputs for the module
#

#-------------#
#  Functions  #
#-------------#

# exit the program and output the error message passed to the function
fatal () {
  echo $1
  exit 1
}

# convert the given filename into title-case for the header
make_title () {
  local input="$1"
  local words
  local word
  local title

  words="${input//[-_]/ }"      # change delimiters to spaces

  for word in $words; do
    title+="${word^} "                # convert first letter of each word to upper
  done
  title="${title% }"                  # trim trailing space

  echo "$title"
}

# create a 3-line header like the one at the top of this file with
# enough dashes to keep each line the same length as the others
make_header () {
  local title="$1"
  local len=${#title}
  local dashes=$(printf '%*s' "$((len + 4))" '' | command tr ' ' '-')
  printf '#%s#\n#  %s  #\n#%s#\n' "$dashes" "$title" "$dashes"
}

#---------#
#  Setup  #
#---------#

# Make sure there's at least 1 argument (the file name)
if [[ $# < 1 ]]
then
  fatal "not enough arguments"
fi

input_path="$1"

if [[ "$1" == */* ]]; then            # if the filename contains a slash
  name="${input_path##*/}"            # trim leading folders from path
  filedir="${input_path%/*}"          # find target file directory
else
  name="${input_path}"
  filedir="$PWD"
fi

filename="${name%%.nix}"              # trim file extension if supplied
title=$(make_title "$filename")

# If this is a default.nix file, disable header
if [[ "${title}" == "Default" ]]; then
  header=""
else
  header=$(make_header "$title")
fi

header_block=${header:+$'\n'$header$'\n'}

shift

if [[ $# == 0 ]]
then
  inputs_string="{ ... }:"            # default value if no inputs are supplied
fi

# Here we create a string formatted as "{ $1, $2, $3, ... }:" containing all arguments
# (if inputs are provided)
if [[ $# > 0 ]]
then 
  inputs_string="{ "
  cfg_support=false;

  # Check whether one of the args is "config". If so, enable cfg support
  for arg in "$@"
  do
    case "$1" in
      "config") inputs_string+="${arg%,}, "; cfg_support=true;;
      "config,") inputs_string+="${arg%,}, "; cfg_support=true;;
      *) inputs_string+="${arg%,}, ";;
    esac
    shift
  done

  inputs_string="$inputs_string... }:"
fi

filepath="${filedir}/$filename.nix"

# if cfg support is enabled, add an extra variable declaration before function body
if [[ $cfg_support == true ]]; then
  cfg_string='  cfg = config;'
else
  cfg_string=""
fi

cfg_block=${cfg_string:+$'\nlet\n'$cfg_string$'\nin\n'}

# Prompt for confirmation if file already exists
if [[ -e "$filepath" ]]; then
    read -r -p "$filepath already exists. Overwrite? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        fatal "aborting"
    fi
fi

#----------#
#  Output  #
#----------#
command cat <<EOF >$filepath
# $filepath
$header_block
$inputs_string
$cfg_block
{

}
EOF

exit 0
